services:
  web-main:
    image: nginx:1.28
    container_name: web-main
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - main-network
    restart: always

  frontend:
    container_name: frontend
    image: nginx:1.28
    networks:
      - main-network
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  main-network: 
    driver: bridge
