server {
    listen       80;
    listen  [::]:80;
    server_name weareithero.cloud;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_cache_bypass $http_upgrade;
    proxy_redirect off;

    error_page 504 /504.html;
    error_page 502 /504.html;

    location = /504.html {
        root /usr/share/nginx/html;
        internal;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_connect_timeout 2s;
    }

}

server {
    listen       80;
    server_name main.weareithero.cloud;

    client_max_body_size 100M;

    # 프록시 요청 타임아웃
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;

    # 서버가 응답을 기다리는 시간
    client_header_timeout 300s;
    client_body_timeout 300s;

    location / {
        proxy_pass http://gateway:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen       80;
    server_name skm.weareithero.cloud;

    client_max_body_size 100M;

    # 프록시 요청 타임아웃
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;

    # 서버가 응답을 기다리는 시간
    client_header_timeout 300s;
    client_body_timeout 300s;

    location / {
        proxy_pass http://gateway:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen       80;
    server_name hg.weareithero.cloud;

    client_max_body_size 100M;

    # 프록시 요청 타임아웃
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;

    # 서버가 응답을 기다리는 시간
    client_header_timeout 300s;
    client_body_timeout 300s;

    location / {
        proxy_pass http://gateway:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen       80;
    server_name tv.weareithero.cloud;

    client_max_body_size 100M;

    # 프록시 요청 타임아웃
    proxy_read_timeout 300s;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;

    # 서버가 응답을 기다리는 시간
    client_header_timeout 300s;
    client_body_timeout 300s;

    location / {
        proxy_pass http://gateway:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
