name: Windows PC Job

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .
      
      - name: Docker Main Down
        working-directory: .
        run: docker compose -f main-system.yml down
        continue-on-error: true

      - name: Docker Main Up
        working-directory: .
        run: docker compose -f main-system.yml up -d

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      
      - name: Docker App Down
        working-directory: .
        run: docker compose -f app-system.yml down
        continue-on-error: true

      - name: Docker App Up
        working-directory: .
        run: docker compose -f app-system.yml up -d
