name: Windows PC Job

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: .
      
      # - name: Docker Main Down
      #   working-directory: ./main
      #   run: docker compose down
      #   continue-on-error: true

      # - name: Docker Main Up
      #   working-directory: ./main
      #   run: docker compose up -d

      - name: Build Frontend
        working-directory: ./app/frontend
        run: |
          npm install
          npm run build

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Gateway
        env: 
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          ROUTE_MAIN_URI: ${{ secrets.ROUTE_MAIN_URI }}
          ROUTE_SKM_URI: ${{ secrets.ROUTE_SKM_URI }}
          ROUTE_HG_URI: ${{ secrets.ROUTE_HG_URI }}
          ROUTE_TV_URI: ${{ secrets.ROUTE_TV_URI }}
        working-directory: ./app/gateway
        run: .\mvnw clean package

      - name: Docker App Down
        working-directory: ./app
        run: docker compose down
        continue-on-error: true

      - name: Docker App Up
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MARIA_DB_DATABASE: ${{ secrets.MARIA_DB_DATABASE }}
          MARIA_DB_USER: ${{ secrets.MARIA_DB_USER }}
          MARIA_DB_PASSWORD: ${{ secrets.MARIA_DB_PASSWORD }}
          MARIA_DB_HOST: ${{ secrets.MARIA_DB_HOST }}
          MARIA_DB_PORT: ${{ secrets.MARIA_DB_PORT }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          REFRESH_TOKEN_EXPIRE_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRE_DAYS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_DB: ${{ secrets.REDIS_DB }}
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        working-directory: ./app
        run: docker compose up -d

      - name: Restart Specific Nginx
        working-directory: ./main
        run: docker compose restart web-main
